export type EventStatus =
  | "SCHEDULED"
  | "CALLING_PERSON"
  | "PERSON_DID_NOT_ANSWER"
  | "CONVERSATION_IN_PROGRESS"
  | "ANALYSING_CONVERSATION"
  | "NO_ACTION_REQUIRED"
  | "ATTENTION_REQUIRED"
  | "CALLING_TRUSTED_CONTACT"
  | "CONTACT_DID_NOT_ANSWER"
  | "CONTACT_DECLINED"
  | "CONTACT_CONFIRMED"
  | "HUMAN_REVIEW_REQUIRED"
  | "CASE_CLOSED";

export type OrchestrationDecision =
  | "NO_ACTION"
  | "LOG_AND_CLOSE"
  | "RETRY_CHECK_IN"
  | "CONTACT_TRUSTED_PERSON"
  | "CONTACT_NEXT_TRUSTED_PERSON"
  | "REQUEST_HUMAN_REVIEW"
  | "ACTIVATE_CONFIGURED_ESCALATION";

export type Priority = "low" | "medium" | "high";

export type TransitionEvent =
  | "COMPANION_CALL_STARTED"
  | "COMPANION_CONVERSATION_STARTED"
  | "COMPANION_PERSON_NO_ANSWER"
  | "COMPANION_CALL_ENDED"
  | "COMPANION_RESULT_NO_ACTION"
  | "COMPANION_RESULT_ATTENTION"
  | "COMPANION_RESULT_MALFORMED"
  | "COMPANION_RESULT_UNCERTAIN"
  | "FAMILY_CALL_STARTED"
  | "FAMILY_NO_ANSWER"
  | "FAMILY_DECLINED"
  | "FAMILY_CONFIRMED"
  | "FAMILY_RESULT_MALFORMED"
  | "FAMILY_CALL_NOT_POSSIBLE"
  | "NO_CONTACTS_REMAINING"
  | "CASE_CLOSED_EVENT";
